"""replace_selectors_with_interactions

Revision ID: f4a0e26497af
Revises: 0001
Create Date: 2026-05-25 11:36:53.425106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4a0e26497af'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('interactions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.drop_column('trackers', 'css_selector')
    op.drop_column('trackers', 'xpath')
    op.drop_constraint('users_auth_provider_id_key', 'users', type_='unique')
    op.drop_index('ix_users_auth_provider_id', table_name='users')
    op.create_index(op.f('ix_users_auth_provider_id'), 'users', ['auth_provider_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_provider_id'), table_name='users')
    op.create_index('ix_users_auth_provider_id', 'users', ['auth_provider_id'], unique=False)
    op.create_unique_constraint('users_auth_provider_id_key', 'users', ['auth_provider_id'])
    op.add_column('trackers', sa.Column('xpath', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('trackers', sa.Column('css_selector', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('trackers', 'interactions')
    # ### end Alembic commands ###
